VehicleUpgrades = {
    "Spoiler Pro", "Spoiler Win", "Spoiler Drag", "Spoiler Alpha", "Maska Champ Scoop", "Maska Fury Scoop", "Dach Scoop", "Prawy próg", "Nitro x5",
    "Nitro x2", "Nitro x10", "Maska Race Scoop", "Maska Worx Scoop", "Lampy okrągłe Fog", "Spoiler Champ", "Spoiler Race", "Spoiler Worx", "Lewy próg",
    "Wydech Upswept", "Wydech Twin", "Wydech duży", "Wydech średni", "Wydech mały", "Spoiler Fury", "Lampy kwadratowe Fog", "Felgi Offroad", "Prawy próg Alien",
    "Lewy próg Alien", "Wydech Alien", "Wydech X-Flow", "Lewy próg X-Flow", "Prawy próg X-Flow", "Dach Alien Vent", "Dach X-Flow Vent", "Wydech Alien", "Dach X-Flow Vent",
    "Prawy próg Alien", "Wydech X-Flow", "Dach Alien Vent", "Lewy próg X-Flow", "Lewy próg Alien", "Prawy próg X-Flow", "Prawy próg Alien", "Wydech Slamin", "Wydech Chrome",
    "Wydech X-Flow", "Wydech Alien", "Prawy próg Alien", "Prawy próg X-Flow", "Spoiler Alien", "Spoiler X-Flow", "Lewy próg Alien", "Lewy próg X-Flow", "Dach X-Flow", "Dach Alien",
    "Dach Alien", "Prawy próg Alien", "Prawy próg X-Flow", "Spoiler Alien", "Wydech X-Flow", "Spoiler X-Flow", "Dach X-Flow", "Lewy próg Alien", "Lewy próg X-Flow", "Wydech Alien",
    "Wydech Alien", "Wydech X-Flow", "Dach Alien", "Dach X-Flow", "Prawy próg Alien", "Prawy próg X-Flow", "Lewy próg Alien", "Lewy próg X-Flow", "Felgi Shadow", "Felgi Mega",
    "Felgi Rimshine", "Felgi Wires", "Felgi Classic", "Felgi Twist", "Felgi Cutter", "Felgi Switch", "Felgi Grove", "Felgi Import", "Felgi Dollar", "Felgi Trance", "Felgi Atomic",
    "Stereo", "Hydraulika", "Dach Alien", "Wydech X-Flow", "Prawy próg Alien", "Dach X-Flow", "Wydech Alien", "Lewy próg X-Flow", "Lewy próg Alien", "Prawy próg X-Flow",
    "Felgi Ahab", "Felgi Virtual", "Felgi Access", "Lewy próg Chrome", "Osłona zderzaka Chrome Grill", "Lewy próg Chrome Flames", "Lewy próg Chrome Strip", "Dach Covertible",
    "Wydech Chrome", "Wydech Slamin", "Prawy próg Chrome Arches", "Lewy próg Chrome Strip", "Prawy próg Chrome Strip", "Tylnie osłony Chrome", "Tylnie osłony Slamin",
    "Front Little Sign", "Front Little Sign 2", "Wydech Chrome", "Wydech Slamin", "Przednie osłony Chrome", "Przednie osłony Slamin", "Przedni zderzak Chrome",
    "Prawy próg Chrome Trim", "Prawy próg Wheelcovers", "Lewy próg Chrome Trim", "Lewy próg Wheelcovers", "Prawy próg Chrome Flames", "Osłony Chrome Bars",
    "Lewy próg Chrome Arches", "Osłony Chrome Lights", "Wydech Chrome", "Wydech Slamin", "Dach Vinyl Hardtop", "Wydech Chrome", "Dach Hardtop", "Dach Softtop",
    "Wydech Slamin", "Prawy próg Chrome Strip", "Prawy próg Chrome Strip", "Wydech Slamin", "Wydech Chrome", "Lewy próg Chrome Strip", "Spoiler Alien", "Spoiler X-Flow",
    "Przedni zderzak X-Flow", "Przedni zderzak Alien", "Lewa okrągła wentylacja", "Prawa okrągła wentylacja", "Lewa kwadratowa wentylacja", "Prawa kwadratowa wentylacja",
    "Spoiler X-Flow", "Spoiler Alien", "Tylni zderzak X-Flow", "Tylni zderzak Alien", "Tylni zderzak Alien", "Tylni zderzak X-Flow", "Przedni zderzak X-Flow",
    "Przedni zderzak Alien", "Tylni zderzak Alien", "Przedni zderzak Alien", "Tylni zderzak X-Flow", "Przedni zderzak X-Flow", "Spoiler X-Flow", "Tylni zderzak Alien",
    "Przedni zderzak Alien", "Tylni zderzak X-Flow", "Spoiler Alien", "Spoiler X-Flow", "Spoiler Alien", "Przedni zderzak X-Flow", "Przedni zderzak Alien", "Tylni zderzak X-Flow",
    "Tylni zderzak Alien", "Przedni zderzak Alien", "Przedni zderzak X-Flow", "Przedni zderzak Alien", "Przedni zderzak X-Flow", "Przedni zderzak X-Flow", "Przedni zderzak Chrome",
    "Przedni zderzak Slamin", "Tylni zderzak Chrome", "Tylni zderzak Slamin", "Tylni zderzak Slamin", "Przedni zderzak Chrome", "Tylni zderzak Chrome", "Przedni zderzak Slamin",
    "Przedni zderzak Chrome", "Tylni zderzak Slamin", "Tylni zderzak Chrome", "Przedni zderzak Slamin", "Tylni zderzak Slamin", "Tylni zderzak Chrome", "Przedni zderzak Slamin",
    "Przedni zderzak Chrome", "Przedni zderzak Slamin", "Przedni zderzak Chrome", "Tylni zderzak Slamin", "Tylni zderzak Chrome"
}
