startPoints = {
    ["visual"] = 9,
    ["performance"] = 7,
}

categories = {
    ["visual"] = {
        {
            name = "Çatı girişleri",
            type = "roof",
            icon = "files/images/roof.png",
            offset = Vector3(2, 2, 0),
            component = "ug_roof",
        },
        {
            name = "Kaputtaki girişler",
            type = "hood",
            icon = "files/images/hood.png",
            offset = Vector3(2, 2, 0),
            component = "bonnet_dummy",
        },
        {
            name = "Ön tampon",
            type = "front bumper",
            icon = "files/images/frontBumper.png",
            offset = Vector3(0, 2, 0),
        },
        {
            name = "Arka tampon",
            type = "rear bumper",
            icon = "files/images/backBumper.png",
            offset = Vector3(0, -2, 0),
        },
        {
            name = "Parçalar",
            type = "sideskirt",
            icon = "files/images/hood.png",
            offset = Vector3(-2, 0, 0),
        },
        {
            name = "Egzoz",
            type = "exhaust",
            icon = "files/images/exhaust.png",
            offset = Vector3(0, -2, 0),
            component = "exhaust_ok",
        },
        {
            name = "Spoiler",
            type = "spoiler",
            icon = "files/images/spoiler.png",
            offset = Vector3(2, -2, 0),
        },
        {
            name = "Tekerlek",
            type = "wheels",
            icon = "files/images/rims.png",
            offset = Vector3(2, 2, 0),
            component = "wheel_lf_dummy",
        },
        {
            name = "Kapat",
            type = "exit",
            icon = "files/images/exit.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
        },
        {
            name = "Işıklar",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            isCustom = true,
            avaliableAll = true,
        },
        {
            name = "Sayaç rengi",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            isCustom = true,
            avaliableAll = true,
        },
        {
            name = "Cam filmi",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            isCustom = true,
            avaliableAll = true,
            isPremium = true,
        },
        {
            name = "Lastik genişletme",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            isCustom = true,
            avaliableAll = true,
            isPremium = true,
        },
        {
            name = "Teker açısı",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            isCustom = true,
            avaliableAll = true,
            isPremium = true,
        },
        {
            name = "Neon",
            type = "neon",
            icon = "files/images/neon.png",
            offset = Vector3(2, 0, 0),
            avaliableAll = true,
            isCustom = true,
            isPremium = true,
        },
        {
            name = "Variant",
            type = "variant",
            icon = "files/images/variant.png",
            offset = Vector3(2, 3, 0),
            isPremium = true,
        },
    },

    ["performance"] = {
        {
            name = "Turbo",
            type = "turbo",
            icon = "files/images/turbo.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "distribution",
            type = "distribution",
            icon = "files/images/distribution.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Pistonlar",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Yakıt enjektörleri",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Soğutucu",
            type = "intercooler",
            icon = "files/images/intercooler.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Debriyaj",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Kapat",
            type = "exit",
            icon = "files/images/exit.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Fren diskleri",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Fren balataları",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Direksiyon sistemi",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Süspansiyon",
            type = "suspension",
            icon = "files/images/suspension.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Tahrik oranı",
            type = "drivetype",
            icon = "files/images/drivetype.png",
            offset = Vector3(0, 2, 0),
            avaliableAll = true,
            isCustom = true,
        },
    },
}

customUpgrades = {
    ["lamps"] = {
        {
            name = "Standard",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            element = {255,255,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "kırmızı",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,0,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Portakal rengi",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,85,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "turuncu",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,170,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "sarı",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Bahar rengi",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {170,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Parlak yeşil",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {85,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Limon rengi",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Koyu yeşil",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,255,85},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "İlkbahar yesili",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,255,170},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Camgöbeği",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,255,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Derin Gök Mavisi",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,170,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Lacivert",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,85,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Mavi",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {0,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Mor",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {85,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Pembe",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {170,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Fuşya",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Hollywood Kirazı",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,0,170},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Açık pembe",
            type = "lamps",
            icon = "files/images/lights.png",
            offset = Vector3(0, 2, 0),
            price = 8500,
            element = {255,0,85},
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["speedoColor"] = {
        {
            name = "Standard",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            element = {255,255,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Kırmızı",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 5200,
            element = {255,0,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Portakal turuncusu",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,85,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "turuncu",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,170,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Sarı",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Açık sarı",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {170,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Yeşil",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {85,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Limon rengi",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,255,0},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Hafif koyu yeşil",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,255,85},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Açık yeşil",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,255,170},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Camgöbeği",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,255,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Derin Gök Mavisi",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,170,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Lacivert",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,85,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Mavi",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {0,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Mor",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {85,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Pembe",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {170,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Fuşya",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,0,255},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Hollywood Kirazı",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,0,170},
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Açık pembe",
            type = "speedoColor",
            icon = "files/images/speedometer.png",
            offset = Vector3(2, -1, 0),
            price = 6200,
            element = {255,0,85},
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["wheelResize"] = {
        {
            name = "Teker boyutu",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            element = 1,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+1",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 4200,
            element = 1.1,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+2",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 5000,
            element = 1.2,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+3",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 6700,
            element = 1.3,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+4",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 7800,
            element = 1.4,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+5",
            type = "wheelResize",
            icon = "files/images/tiresize.png",
            offset = Vector3(2, 4, 0),
            price = 9000,
            element = 1.5,
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["wheelTilt"] = {
        {
            name = "Tekerler",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            element = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+1",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 4900,
            element = -1,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+2",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 5900,
            element = -2,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+3",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 7200,
            element = -3,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+4",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 8400,
            element = -4,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+5",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 9700,
            element = -5,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+6",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 10250,
            element = -6,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+7",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 11400,
            element = -7,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+8",
            type = "wheelTilt",
            icon = "files/images/wheeltilt.png",
            offset = Vector3(2, 4, 0),
            price = 12500,
            element = -8,
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["glassTint"] = {
        {
            name = "Brak",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            element = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "95%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 4200,
            element = 0.05,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "90%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 5700,
            element = 0.1,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "80%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 7200,
            element = 0.2,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "70%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 8200,
            element = 0.3,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "60%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 9100,
            element = 0.4,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "50%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 10000,
            element = 0.5,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "40%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 11200,
            element = 0.6,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "30%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 12400,
            element = 0.7,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "20%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 13500,
            element = 0.8,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "10%",
            type = "glassTint",
            icon = "files/images/windowtint.png",
            offset = Vector3(2, 1, 0),
            price = 14000,
            element = 0.9,
            avaliableAll = true,
            isCustom = true,
        },
    },

    ["turbo"] = {
        {
            name = "Brak",
            type = "turbo",
            icon = "files/images/turbo.png",
            offset = Vector3(0, 2, 0),
            element = false,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "1 Turbina",
            type = "turbo",
            icon = "files/images/turbo.png",
            offset = Vector3(0, 2, 0),
            element = "Turbo",
            value = 0.5,
            avaliableAll = true,
            isCustom = true,
            price = 38500,
        },
        {
            name = "2 Turbiny",
            type = "turbo",
            icon = "files/images/turbo.png",
            element = "Biturbo",
            offset = Vector3(0, 2, 0),
            value = 1,
            avaliableAll = true,
            isCustom = true,
            price = 52500,
        },
    },

    ["distribution"] = {
        {
            name = "Sıradan",
            type = "distribution",
            icon = "files/images/distribution.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Güçlendirilmiş",
            type = "distribution",
            icon = "files/images/distribution.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 8400,
        },
        {
            name = "Bilenmiş",
            type = "distribution",
            icon = "files/images/distribution.png",
            offset = Vector3(0, 2, 0),
            value = 0.4,
            avaliableAll = true,
            isCustom = true,
            price = 9700,
        },
    },

    ["piston"] = {
        {
            name = "Alüminyum",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Çelik",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 8400,
        },
        {
            name = "Dökme demir",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            value = 0.4,
            avaliableAll = true,
            isCustom = true,
            price = 9300,
        },
        {
            name = "Yaldızlı",
            type = "piston",
            icon = "files/images/piston.png",
            offset = Vector3(0, 2, 0),
            value = 0.6,
            avaliableAll = true,
            isCustom = true,
            price = 13000,
        },
    },

    ["injection"] = {
        {
            name = "Standard",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+10 mm",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 8500,
        },
        {
            name = "+20 mm",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0.4,
            avaliableAll = true,
            isCustom = true,
            price = 9500,
        },
        {
            name = "+30 mm",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0.6,
            avaliableAll = true,
            isCustom = true,
            price = 12200,
        },
        {
            name = "+40 mm",
            type = "injection",
            icon = "files/images/injection.png",
            offset = Vector3(0, 2, 0),
            value = 0.8,
            avaliableAll = true,
            isCustom = true,
            price = 17800,
        },
    },

    ["intercooler"] = {
        {
            name = "Küçük",
            type = "intercooler",
            icon = "files/images/intercooler.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Vasat",
            type = "intercooler",
            icon = "files/images/intercooler.png",
            offset = Vector3(0, 2, 0),
            value = 0.1,
            avaliableAll = true,
            isCustom = true,
            price = 7400,
        },
        {
            name = "Büyük",
            type = "intercooler",
            icon = "files/images/intercooler.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 8900,
        },
    },

    ["clutch"] = {
        {
            name = "Standard",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Rahat",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            value = -0.2,
            avaliableAll = true,
            isCustom = true,
            price = 5400,
        },
        {
            name = "Spor Dalları",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            value = 0.1,
            avaliableAll = true,
            isCustom = true,
            price = 6400,
        },
        {
            name = "İzlemek",
            type = "clutch",
            icon = "files/images/clutch.png",
            offset = Vector3(0, 2, 0),
            value = 0.2,
            avaliableAll = true,
            isCustom = true,
            price = 7800,
        },
    },

    ["breaking"] = {
        {
            name = "Standard",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Rahat",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            value = -0.5,
            avaliableAll = true,
            isCustom = true,
            price = 4200,
        },
        {
            name = "Spor Dalları",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            value = 0.5,
            avaliableAll = true,
            isCustom = true,
            price = 5700,
        },
        {
            name = "İzlemek",
            type = "breaking",
            icon = "files/images/break.png",
            offset = Vector3(0, 2, 0),
            value = 1,
            avaliableAll = true,
            isCustom = true,
            price = 7100,
        },
    },

    ["breakpad"] = {
        {
            name = "Standard",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Rahat",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            value = -0.5,
            avaliableAll = true,
            isCustom = true,
            price = 4200,
        },
        {
            name = "Spor Dalları",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            value = 0.5,
            avaliableAll = true,
            isCustom = true,
            price = 5300,
        },
        {
            name = "İzlemek",
            type = "breakpad",
            icon = "files/images/breakpad.png",
            offset = Vector3(0, 2, 0),
            value = 1,
            avaliableAll = true,
            isCustom = true,
            price = 6400,
        },
    },

    ["steering"] = {
        {
            name = "Standard",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 0,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "+5",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 5,
            avaliableAll = true,
            isCustom = true,
            price = 8500,
        },
        {
            name = "+10",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 10,
            avaliableAll = true,
            isCustom = true,
            price = 9400,
        },
        {
            name = "+15",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 15,
            avaliableAll = true,
            isCustom = true,
            price = 11000,
        },
        {
            name = "+20",
            type = "steering",
            icon = "files/images/steering.png",
            offset = Vector3(0, 2, 0),
            value = 20,
            avaliableAll = true,
            isCustom = true,
            price = 13400,
        },
    },

    ["suspension"] = {
        {
            name = "Standard",
            type = "suspension",
            icon = "files/images/suspension.png",
            offset = Vector3(0, 2, 0),
            value = false,
            avaliableAll = true,
            isCustom = true,
        },
        {
            name = "Hidrolik",
            type = "suspension",
            icon = "files/images/suspension.png",
            offset = Vector3(0, 2, 0),
            value = 1087,
            avaliableAll = true,
            isCustom = true,
            price = 20400,
        },
        {
            name = "Pnömatik",
            type = "suspension",
            icon = "files/images/suspension.png",
            offset = Vector3(0, 2, 0),
            value = true,
            avaliableAll = true,
            isCustom = true,
            price = 26000,
        },
    },

    ["drivetype"] = {
        {
            name = "Önden çekiş",
            type = "drivetype",
            icon = "files/images/drivetype.png",
            offset = Vector3(0, 2, 0),
            value = "fwd",
            avaliableAll = true,
            isCustom = true,
            price = 34800,
        },
        {
            name = "Arkadan çekişli",
            type = "drivetype",
            icon = "files/images/drivetype.png",
            offset = Vector3(0, 2, 0),
            value = "rwd",
            avaliableAll = true,
            isCustom = true,
            price = 36200,
        },
        {
            name = "4x4",
            type = "drivetype",
            icon = "files/images/drivetype.png",
            offset = Vector3(0, 2, 0),
            value = "awd",
            avaliableAll = true,
            isCustom = true,
            price = 42200,
        },
    },
}


function getCustomUpgrades()
    return customUpgrades
end

neonColors = {
    {255, 0, 0, "Kırmızı"},
    {255, 85, 0, "Portakal turuncusu"},
    {255, 170, 0, "turuncu"},
    {255, 255, 0, "Sarı"},
    {170, 255, 0, "Açık sarı"},
    {85, 255, 0, "Yeşil"},
    {0, 255, 0, "Limon rengi"},
    {0, 255, 85, "Hafif koyu yeşil"},
    {0, 255, 170, "Açık yeşil"},
    {0, 255, 255, "Camgöbeği"},
    {0, 170, 255, "Derin Gök Mavisi"},
    {0, 85, 255, "Lacivert"},
    {0, 0, 255, "Mavi"},
    {85, 0, 255, "Mor"},
    {170, 0, 255, "Pembe"},
    {255, 0, 255, "Fuşya"},
    {255, 0, 170, "Hollywood Kirazı"},
    {255, 0, 85, "Açık pembe"},
}

performanceValuesMax = {
    ["engineAcceleration"] = 50,
    ["maxVelocity"] = 450,
    ["tractionMultiplier"] = 1.6,
    ["brakeDeceleration"] = 35,
    ["steeringLock"] = 60,
    ["fuelTake"] = 50,
}

upgradeNames = {
    "Pro", "Win", "Drag", "Alpha", "Champ Scoop", "Fury Scoop", "Scoop", "Próg", "Nitro x5",
    "Nitro x2", "Nitro x10", "Race Scoop", "Worx Scoop", "okrągłe Fog", "Champ", "Race", "Worx", "Próg",
    "Upswept", "Twin", "duży", "średni", "mały", "Fury", "kwadratowe Fog", "Offroad", "Alien",
    "Alien", "Alien", "X-Flow", "X-Flow", "X-Flow", "Alien Vent", "X-Flow Vent", "Alien", "X-Flow Vent",
    "Alien", "WydeExhaustch X-Flow", "Alien Vent", "X-Flow", "Alien", "X-Flow", "Alien", "Slamin", "Chrome",
    "X-Flow", "Alien", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "X-Flow", "Alien",
    "Alien", "Alien", "X-Flow", "Alien", "X-Flow", "X-Flow", "X-Flow", "Alien", "X-Flow", "Alien",
    "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "Shadow", "Mega",
    "Rimshine", "Wires", "Classic", "Twist", "Cutter", "Switch", "Grove", "Import", "Dollar", "Trance", "Atomic",
    "Stereo", "Hydraulika", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow",
    "Ahab", "Virtual", "Access", "Chrome", "Osłona zderzaka Chrome Grill", "Chrome Flames", "Chrome Strip", "Covertible",
    "Chrome", "Slamin", "Chrome Arches", "Chrome Strip", "Chrome Strip", "Chrome", "Slamin",
    "Front Little Sign", "Front Little Sign 2", "Chrome", "Slamin", "Przednie osłony Chrome", "Przednie osłony Slamin", "Chrome",
    "Chrome Trim", "Wheelcovers", "Chrome Trim", "Wheelcovers", "Chrome Flames", "Osłony Chrome Bars",
    "Chrome Arches", "Osłony Chrome Lights", "Chrome", "Slamin", "Vinyl Hardtop", "Chrome", "Hardtop", "Softtop",
    "Slamin", "Chrome Strip", "Chrome Strip", "Slamin", "Chrome", "Chrome Strip", "Alien", "X-Flow",
    "X-Flow", "Alien", "Okrągła wentylacja", "Okrągła wentylacja", "kwadratowa wentylacja", "kwadratowa wentylacja",
    "X-Flow", "Alien", "X-Flow", "Alien", "Alien", "X-Flow", "X-Flow",
    "Alien", "Alien", "Alien", "X-Flow", "X-Flow", "X-Flow", "Alien",
    "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow", "Alien", "X-Flow",
    "Alien", "Alien", "X-Flow", "Alien", "X-Flow", "X-Flow", "Chrome",
    "Slamin", "Chrome", "Slamin", "Slamin", "Chrome", "Chrome", "Slamin",
    "Chrome", "Slamin", "Chrome", "Slamin", "Slamin", "Chrome", "Slamin",
    "Chrome", "Slamin", "Chrome", "Slamin", "Chrome"
}

prices = {
    [1025]=52000,
    [1073]=51000,
    [1074]=46000,
    [1075]=46000,
    [1076]=44000,
    [1077]=47000,
    [1078]=49000,
    [1079]=44000,
    [1080]=48000,
    [1081]=52000,
    [1082]=49000,
    [1083]=55000,
    [1084]=53000,
    [1085]=46000,
    [1097]=48000,


--  Stereo
	[1086]=3000,
--  Spoilery
	[1000]=20000,
	[1001]=25000,
	[1002]=20000,
	[1003]=25000,
	[1014]=14000,
	[1015]=20000,
	[1016]=21000,
	[1023]=24000,
	[1049]=15400,
	[1050]=13000,
	[1058]=13000,
	[1060]=17500,
	[1138]=39000,
	[1139]=34000,
	[1146]=30000,
	[1147]=35500,
	[1158]=41000,
	[1162]=29000,
	[1163]=20000,
	[1164]=45000,
--	Progi
	[1036]=15000,
	[1039]=20000,
	[1040]=18700,
	[1041]=23000,
	[1007]=10000,
	[1017]=10000,
	[1026]=15000,
	[1027]=20000,
	[1030]=15000,
	[1031]=23000,
	[1042]=10000,
	[1047]=18900,
	[1048]=17300,
	[1051]=20000,
	[1052]=18000,
	[1056]=10000,
	[1057]=10000,
	[1062]=10000,
	[1063]=12500,
	[1069]=18000,
	[1070]=15000,
	[1071]=16500,
	[1072]=17500,
	[1090]=17500,
	[1093]=17000,
	[1094]=15000,
	[1095]=10000,
	[1099]=10000,
	[1101]=10000,
	[1102]=7000,
	[1106]=10000,
	[1107]=10000,
	[1108]=10000,
	[1118]=7000,
	[1119]=7000,
	[1120]=7000,
	[1121]=7000,
	[1122]=7000,
	[1124]=7000,
	[1133]=10000,
	[1134]=10000,
	[1137]=10000,

--  Bullbar . . ? [przod]
	[1100]=7500,
	[1115]=7500,
	[1116]=7500,
	[1123]=7500,
	[1125]=10000,
--  Bullbar . . ? [tył]
	[1109]=9000,
	[1110]=3000,
--	Front Sign [figurka itd z przodu]
	[1111]=6500,
	[1112]=6500,
--	Hydraulika
	[1087]=35100,
--  Wydechy
	[1034]=19000,
	[1037]=20000,
	[1044]=18000,
	[1046]=20000,
	[1018]=17000,
	[1019]=19000,
	[1020]=20000,
	[1021]=18000,
	[1022]=18000,
	[1028]=19000,
	[1029]=20000,
	[1043]=15000,
	[1044]=10000,
	[1045]=15000,
	[1059]=15000,
	[1064]=12000,
	[1065]=13000,
	[1066]=15000,
	[1089]=20000,
	[1092]=17500,
	[1104]=16500,
	[1105]=14500,
	[1113]=12000,
	[1114]=17500,
	[1126]=10000,
	[1127]=11000,
	[1129]=10000,
	[1132]=15000,
	[1135]=10000,
	[1136]=15000,

--  Zderzaki [tylni]
	[1149]=40000,
	[1148]=50000,
	[1150]=30000,
	[1151]=35000,
	[1154]=30000,
	[1156]=30000,
	[1159]=35000,
	[1161]=36000,
	[1167]=30000,
	[1168]=25000,
	[1175]=25000,
	[1177]=25000,
	[1178]=29000,
	[1180]=31000,
	[1183]=27000,
	[1184]=30000,
	[1186]=30000,
	[1187]=26000,
	[1192]=20000,
	[1193]=20000,
--  Zderzaki [pzrzód]
	[1171]=35000,
	[1172]=50000,
	[1140]=35000,
	[1141]=50000,
	[1117]=5000,
	[1152]=30000,
	[1153]=35000,
	[1155]=30000,
	[1153]=30000,
	[1157]=30000,
	[1160]=40000,
	[1165]=40000,
	[1166]=30000,
	[1169]=30000,
	[1170]=35000,
	[1173]=35000,
	[1174]=25000,
	[1176]=25000,
	[1179]=35000,
	[1181]=25000,
	[1182]=23000,
	[1185]=30000,
	[1188]=32000,
	[1189]=29000,
	[1190]=25000,
	[1191]=21000,
--  Wloty [góra]
	[1035]=30000,
	[1038]=35000,
	[1006]=19600,
	[1032]=30000,
	[1033]=35000,
	[1053]=35000,
	[1054]=30000,
	[1055]=20000,
	[1061]=20000,
	[1068]=32500,
	[1067]=27500,
	[1088]=23000,
	[1091]=30000,
	[1103]=15000,
	[1128]=50000, -- DACH DO BLADE
	[1130]=50000, -- DACH DO SAVANNA
	[1131]=50000, -- DACH DO SAVANNA
--  Wloty [przód]
	[1004]=14000,
	[1005]=16000,
	[1011]=14000,
	[1012]=16000,
	[1142]=12000,
	[1143]=12000,
	[1144]=10000,
	[1145]=10000,
--	Dodatkowe lampy
	[1013]=7000,
	[1024]=8000,
}
