
local txd = engineLoadTXD("pumpkin.txd")
			engineImportTXD(txd, 8981)
local dff = engineLoadDFF("pumpkin.dff", 8981)
			engineReplaceModel(dff, 8981)
local col = engineLoadCOL ( "pumpkin.col" )
			engineReplaceCOL ( col, 8981)
--------------------------------------------------------------
local txd = engineLoadTXD("kruton9000.txd")
			engineImportTXD(txd, 2014)
local dff = engineLoadDFF("kruton9000.dff", 2014)
			engineReplaceModel(dff, 2014)
local col = engineLoadCOL ( "kruton9000.col" )
			engineReplaceCOL ( col, 2014)
--------------------------------------------------------------
local txd = engineLoadTXD("ramp.txd")
			engineImportTXD(txd, 2015)
local dff = engineLoadDFF("ramp.dff", 2015)
			engineReplaceModel(dff, 2015)
local col = engineLoadCOL ( "ramp.col" )
			engineReplaceCOL ( col, 2015)
--------------------------------------------------------------
local txd = engineLoadTXD("welder.txd")
			engineImportTXD(txd, 2016)
local dff = engineLoadDFF("welder.dff", 2016)
			engineReplaceModel(dff, 2016)
local col = engineLoadCOL ( "welder.col" )
			engineReplaceCOL ( col, 2016)
--------------------------------------------------------------
local txd = engineLoadTXD("dev_tool.txd")
			engineImportTXD(txd, 2018)
local dff = engineLoadDFF("dev_tool.dff", 2018)
			engineReplaceModel(dff, 2018)
local col = engineLoadCOL ( "dev_tool.col" )
			engineReplaceCOL ( col, 2018)
--------------------------------------------------------------
local txd = engineLoadTXD("dev_tool2.txd")
			engineImportTXD(txd, 2019)
local dff = engineLoadDFF("dev_tool2.dff", 2019)
			engineReplaceModel(dff, 2019)
local col = engineLoadCOL ( "dev_tool2.col" )
			engineReplaceCOL ( col, 2019)
--------------------------------------------------------------
local txd = engineLoadTXD("dev_tool3.txd")
			engineImportTXD(txd, 2020)
local dff = engineLoadDFF("dev_tool3.dff", 2020)
			engineReplaceModel(dff, 2020)
local col = engineLoadCOL ( "dev_tool3.col" )
			engineReplaceCOL ( col, 2020)
--------------------------------------------------------------
local txd = engineLoadTXD("tire.txd")
			engineImportTXD(txd, 2021)
local dff = engineLoadDFF("tire.dff", 2021)
			engineReplaceModel(dff, 2021)
local col = engineLoadCOL ( "tire.col" )
			engineReplaceCOL ( col, 2021)
--------------------------------------------------------------
local txd = engineLoadTXD("tire2.txd")
			engineImportTXD(txd, 2022)
local dff = engineLoadDFF("tire2.dff", 2022)
			engineReplaceModel(dff, 2022)
local col = engineLoadCOL ( "tire2.col" )
			engineReplaceCOL ( col, 2022)
--------------------------------------------------------------
local txd = engineLoadTXD("tools.txd")
			engineImportTXD(txd, 1630)
local dff = engineLoadDFF("tools.dff", 1630)
			engineReplaceModel(dff, 1630)
local col = engineLoadCOL ( "tools.col" )
			engineReplaceCOL ( col, 1630)
--------------------------------------------------------------
local txd = engineLoadTXD("choinka.txd")
			engineImportTXD(txd, 18000)
local dff = engineLoadDFF("choinka.dff", 18000)
			engineReplaceModel(dff, 18000)
local col = engineLoadCOL ( "choinka.col" )
			engineReplaceCOL ( col, 18000)
--------------------------------------------------------------
-- local txd = engineLoadTXD("prezenty.txd")
-- 			engineImportTXD(txd, 1942)
-- local dff = engineLoadDFF("prezenty.dff", 1942)
-- 			engineReplaceModel(dff, 1942)
-- local col = engineLoadCOL ( "prezenty.col" )
-- 			engineReplaceCOL ( col, 1942)
--------------------------------------------------------------
local dff = engineLoadDFF("bench1.dff", 14401)
			engineReplaceModel(dff, 14401)
local col = engineLoadCOL ( "bench1.col" )
			engineReplaceCOL ( col, 14401)
--------------------------------------------------------------
local txd = engineLoadTXD("chlights.txd")
			engineImportTXD(txd, 1911)
local dff = engineLoadDFF("chlights.dff", 1911)
			engineReplaceModel(dff, 1911)
local col = engineLoadCOL ( "chlights.col" )
			engineReplaceCOL ( col, 1911)
--------------------------------------------------------------
local txd = engineLoadTXD("snowmen.txd")
			engineImportTXD(txd, 1921)
local dff = engineLoadDFF("snowmen.dff", 1921)
			engineReplaceModel(dff, 1921)
local col = engineLoadCOL ( "snowmen.col" )
			engineReplaceCOL ( col, 1921)
